apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 5 # 5 despliegues
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: vjimcor955/fastapi-k8s # Asegúrate de usar tu imagen
          ports:
            - containerPort: 8000
