apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80 # Puerto externo
      targetPort: 8000 # Puerto del contenedor
  type: LoadBalancer
